//     7. Create an interface called Rollable 
//    * abstract void method roll 
//    * Circle implements Rollable
//  Finally, Create anon-apex file 
//  Create object of all things you can create object out of. 
//  Create a List of Shape add all different Shapes 
//  Create Drawable and assign object to it 
//  Call the methods and print the results


public interface Rollable {

void roll();

}
