//9. Write a program that takes a list of strings that represent the names of account owners,
// and counts the number of times jon snow appears in the list.

List<String> accountOwners = new List<String>{'John White', 'Andy Young', 'Jon Snow', 'Avi Green', 'Jane Gray',
                                            'Jon Snow', 'Josh Davis'};

 for(){
    
 }                                           